# Site settings
title_left    : "ae"
title_right   : "ged" # default: ""
description   : "Alexander Gednov's personal website for projects, blogging, etc."
keywords      : "Jekyll, theme, free, download, SEO, blog, web, minimalist, thinkspace"
url           : https://aeged.github.io/ # site url
baseurl       : "" # apply repo name like "/myproject" if used under gh-pages branch, else (under master branch) just leave empty/blank
cover         : "./assets/icons/MyIcons/light-flask.svg" # image uri like logo/cover image for site seo

google_analytics  : UA-XXXXX-XX
twitter_username  : ""
comments_enabled  : false # if enabled (set to true), please provide your disqus_username
disqus_shortname  : ""
postshare_enabled : false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
kramdown:
  input:          GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

source      : ./
destination : ./_site

# Sass configuration
sass:
  sass_dir  : assets/scss
  style     : compressed # expanded

# Author settings
author:
  name     : "Alexander Gednov"

plugins:
  - jekyll-sitemap
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : contact
    title: Contact
  - slug : projects
    title: Projects
  - slug : blog
    title: Blog

# Change all these values or delete the ones you don't want (these appear in the footer).
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: "aeged"
  email: "alexgednov@gmail.com"
  github: aeged
  facebook: yourname  # eg. daattali
  twitter: yourname   # eg. daattali

# Select which links to show in the footer
footer-links-active:
  github: true
  email: true
  rss: false
  facebook: false
  twitter: false

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md", "script"]
